default: &default
  store_options: &default_store_options
    # Cap age of oldest cache entry to fulfill retention policies
    # max_age: <%= 60.days.to_i %>
    max_size: <%= 256.megabytes %>
    namespace: <%= Rails.env %>
    size_estimate_samples: 1000

development: &development
  database: cache
  store_options:
    <<: *default_store_options
    max_size: <%= 256.gigabytes %>

test:
  <<: *default

production:
  <<: *default
