development: &defaults
  adapter: postgresql
  encoding: utf8
  database: <%= Rails.application.secrets.DB_DATABASE %>
  username: <%= Rails.application.secrets.DB_USERNAME %>
  password: <%= Rails.application.secrets.DB_PASSWORD %>
  host: <%= Rails.application.secrets.DB_HOST %>
  pool: 5
  timeout: 5000

production:
  url:

test:
  adapter: postgresql
  encoding: utf8
  database: <%= Rails.application.secrets.DB_DATABASE_TEST %>
  username: <%= Rails.application.secrets.DB_USERNAME_TEST %>
  password: <%= Rails.application.secrets.DB_PASSWORD_TEST %>
  host: <%= Rails.application.secrets.DB_HOST_TEST %>
  pool: 5
  timeout: 5000
